
services:
  api:
    build: ./backend
    container_name: api
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres
    container_name: rides_db
    ports:
      - 5430:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=transporteparticular
  site:
    build: ./frontend
    container_name: app-rides
    ports:
      - 80:80
    depends_on:
      - db
      - api